# Penambangan Data

## Tugas 1

In [2]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
plt.ion()

In [ ]:
dataseturl="https://raw.githubusercontent.com/errjak/dataset/main/202004-divvy-tripdata.csv"
data=pd.read_csv(dataseturl)

In [ ]:
data.head(4)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:14,2020-04-26 18:12:03,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:54,2020-04-17 17:17:03,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:13,2020-04-01 18:08:36,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:19,2020-04-07 13:02:31,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member

### Menghitung Dissimialirity

In [ ]:
def diss (n,m):
  a = 2
  b = 0
  for col in ['start_lat','end_lat']:
    if data[col][n] == data[col][m]:
      b+=1
  return (a-b)/a

In [ ]:
print(diss(1,1))
print(diss(1,2))
print(diss(4,4))

0.0
1.0
0.0

## Tugas 2

In [3]:
dataset = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data = pd.read_csv(dataset)

In [4]:
data.head(-1)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica

[149 rows x 5 columns]

### DISKRITISASI

In [5]:
from sklearn.preprocessing import KBinsDiscretizer

In [6]:
sepalLength = data.sepal_length
sepalWidth = data.sepal_width
petalLength = data.petal_length
petalWidth = data.petal_width
spesies = data.species

In [7]:
aa = sepalLength.values.reshape(-1,1)
ab = sepalWidth.values.reshape(-1,1)
ac = petalLength.values.reshape(-1,1)
ad = petalWidth.values.reshape(-1,1)
sp = spesies.values.reshape(-1,1)

In [8]:
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [9]:
est.fit(aa)
est.fit(ab)
est.fit(ac)
est.fit(ad)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [10]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [11]:
xa = est.transform(aa)
xb = est.transform(ab)
xc = est.transform(ac)
xd = est.transform(ad)

In [12]:
dataa1 = {'sepal_length':xa}
dataa2 = {'sepal_length':xb}
dataa3 = {'sepal_length':xc}
dataa4 = {'sepal_length':xd}

In [13]:
fa = pd.DataFrame(xa,columns=['sepal_length'])
fb = pd.DataFrame(xb,columns=['sepal_width'])
fc = pd.DataFrame(xc,columns=['tepal_length'])
fd = pd.DataFrame(xd,columns=['tepal_width'])
spe = pd.DataFrame(sp,columns=['Species'])

In [14]:
datalist = [fa, fb, fc, fd, spe]
pd.concat(datalist, axis=1)

     sepal_length  sepal_width  tepal_length  tepal_width    Species
0             3.0          3.0           2.0          0.0     setosa
1             3.0          3.0           2.0          0.0     setosa
2             3.0          3.0           2.0          0.0     setosa
3             3.0          3.0           2.0          0.0     setosa
4             3.0          3.0           2.0          0.0     setosa
..            ...          ...           ...          ...        ...
145           3.0          3.0           3.0          3.0  virginica
146           3.0          3.0           3.0          3.0  virginica
147           3.0          3.0           3.0          3.0  virginica
148           3.0          3.0           3.0          3.0  virginica
149           3.0          3.0           3.0          2.0  virginica

[150 rows x 5 columns]